version: '3.8'  # Docker Compose version

services:
  app:
    image: node:12.2.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    command: sh -c "npm install && node app.js"
